class Solution {
public:
    vector<vector<int>> permuteUnique(vector<int>& nums) {
        sort(nums.begin(), nums.end());
        vector<vector<int>> result;
        vector<bool> used(nums.size(), false);
        vector<int> path;
        permute_help(result, nums, used, path);
        return result;
    }

private:
    void permute_help(vector<vector<int>> &result, vector<int> &nums, vector<bool> used, vector<int> path) {
        if (path.size() == nums.size()) {
            result.push_back(path);
            return;
        }
        int i = 0;
        while (i < nums.size()) {
            if (!used[i]) {
                used[i] = true;
                path.push_back(nums[i]);
                permute_help(result, nums, used, path);
                path.pop_back();
                used[i] = false;

                /*  cut branches generated by elements with same value
                	for a series of elements with same value, only the first will be used
                */
                ++i;
                while (i < nums.size() && nums[i] == nums[i - 1])
                    ++i;
            } else
                ++i;
        }
    }
};